spring:
  application:
    name: TransitTrack
  datasource:
    url: jdbc:postgresql://localhost:5432/transitclock
    username: postgres
    password: transitclock
    batch-size: 4_000
    hikari:
      auto-commit: false
      idle-timeout: 30_000
      minimum-idle: 5
      maximum-pool-size: 20
      keepalive-time: 30_000
  jpa:
    generate-ddl: false
    show-sql: false
    properties.hibernate.format_sql: false
    hibernate.ddl-auto: none
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration
  main:
    lazy-initialization: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: 8080

transitclock:
  factory:
    headway-generator: org.transitclock.core.headwaygenerator.LastArrivalsHeadwayGenerator
    prediction-generator: org.transitclock.core.prediction.PredictionGeneratorDefaultImpl
    arrival-departure-generator: org.transitclock.core.avl.ad.ArrivalDepartureGeneratorDefaultImpl
  api:
    gtfsRtCacheSeconds: 15
    includeTripUpdateDelay: false
    predictionMaxFutureSecs: 3600
  arrivalsDepartures:
    allowableDifferenceBetweenAvlTimeSecs: 86400
    maxStopsBetweenMatches: 12
    maxStopsWhenNoPreviousMatch: 1
  autoBlockAssigner:
    allowableEarlySeconds: 180
    allowableLateSeconds: 300
    autoAssignerEnabled: false
    ignoreAvlAssignments: false
    minDistanceFromCurrentReport: 100.0
    minTimeBetweenAutoAssigningSecs: 30
  avl:
#    authenticationPassword: 'null'
#    authenticationUser: 'null'
#    url: 'null'
    gtfsRealtimeFeedURI: https://api.opentransport.ro/exporter/v1/realtime/stpt/vehicle-positions
    feedTimeoutInMSecs: 30000
    maxSpeed: 100
    numThreads: 1
    queueSize: 2400
    minLatitude: 43.0
    maxLatitude: 48.0
    maxLongitude: 30.0
    minLongitude: 20.0
    feedPollingRateSecs: 15

    alternativemaxspeed: 15.0
    maxStopPathsAhead: 999
    minSpeedForValidHeading: 1.5
    minTimeBetweenAvlReportsSecs: 5
    processInRealTime: false
    shouldProcessAvl: true
    unpredictableAssignmentsRegEx: ''
  core:
    agencyId: 'transitclock' # please change this to your agency id
    afterStopDistance: 50.0
    allowableBadAssignments: 4
    allowableEarlyDepartureTimeForLoggingEvent: 60
    allowableEarlyForLayoverSeconds: 3600
    allowableEarlySeconds: 900
    allowableEarlySecondsForInitialMatching: 600
    allowableEarlyTimeForEarlyDepartureSecs: 600
    allowableLateAtTerminalForLoggingEvent: 600
    allowableLateDepartureTimeForLoggingEvent: 240
    allowableLateSeconds: 5400
    allowableLateSecondsForInitialMatching: 1200
    allowableNumberOfBadMatches: 2
    avlHistoryMaxSize: 20
    beforeStopDistance: 50.0
    blockactiveForTimeAfterSecs: -1
    blockactiveForTimeBeforeSecs: 0
    cache:
      daysPopulateHistoricalCache: 0
      tripDataHistoryCache: org.transitclock.core.dataCache.ehcache.scheduled.TripDataHistoryCache
      errorCacheClass: org.transitclock.core.dataCache.ehcache.KalmanErrorCache
      stopArrivalDepartureCache: org.transitclock.core.dataCache.ehcache.StopArrivalDepartureCache
      stopPathPredictionCache: org.transitclock.core.dataCache.StopPathPredictionCache
      dwellTimeModelCache: org.transitclock.core.dataCache.ehcache.scheduled.DwellTimeModelCache
    dwelltime:
      model: org.transitclock.core.prediction.scheduled.dwell.DwellAverage
      headwayGeneratorClass: org.transitclock.core.headwaygenerator.LastArrivalsHeadwayGenerator
    cacheReloadEndTimeStr: ''
    cacheReloadStartTimeStr: ''
    deadheadingShortVersusLongDistance: 1000.0
    defaultBreakTimeSec: 0
    distanceBetweenAvlsForInitialMatchingWithoutHeading: 100.0
    distanceFromEndOfBlockForInitialMatching: 250.0
    distanceFromLastStopForEndMatching: 250.0
    distanceFromLayoverForEarlyDeparture: 180.0
    earlyToLateRatio: 3.0
    emailMessagesWhenAssignmentGrabImproper: false
    eventHistoryMaxSize: 20
    exclusiveBlockAssignments: true
    frequency:
      cacheIncrementsForFrequencyService: 10800
      maxDwellTimeFilterValue: 600000
      maxTravelTimeFilterValue: 600000
      minDwellTimeFilterValue: 0
      minTravelTimeFilterValue: 0
    generateHoldingTimeWhenPredictionWithin: 0
    ignoreInactiveBlocks: true
    layoverDistance: 2000.0
    longDistanceDeadheadingSpeed: 10.0
    matchHistoryMaxSize: 20
    maxDistanceForAssignmentGrab: 10000.0
    maxDistanceFromSegment: 60.0
    maxDistanceFromSegmentForAutoAssigning: 60.0
    maxDwellTime: 600000
    maxHeadingOffsetFromSegment: 360.0
    maxLateCutoffPredsForNextTripsSecs: 2147483647
    maxMatchDistanceFromAVLRecord: 500.0
    maxPredictionTimeForDbSecs: 1800
    maxPredictionsTimeSecs: 1800
    minDistanceForDelayed: 60.0
    minDistanceForNoProgress: 60.0
    onlyNeedArrivalDepartures: false
    pauseIfDbQueueFilling: false
    shortDistanceDeadheadingSpeed: 4.0
    spatialMatchToLayoversAllowedForAutoAssignment: false
    storeDataInDatabase: true
    storeDwellTimeStopPathPredictions: false
    storeTravelTimeStopPathPredictions: false
    terminalDistanceForRouteMatching: 100.0
    timeForDeterminingDelayedSecs: 240
    timeForDeterminingNoProgress: 480000
#    timezone: 'null'
    useArrivalPredictionsForNormalStops: true
    useExactSchedTimeForWaitStops: true
    useHoldingTimeInPrediction: false
    prediction-generator:
      bias:
        exponential:
          a: 0.5
          b: 1.1
          c: -0.5
          updown: -1
        linear:
          rate: 6.0E-4
          updown: -1
    agressive-block-loading: false
  gtfs:
    url: https://data.opentransport.ro/routing/gtfs/gtfs-stpt.zip
    dirName: /var/transitclock/cache
    intervalMsec: 86400000
#    auto-update:
#      enabled: true
#      url:
#      dirName: 'null'
#      intervalMsec: 14400000
#    blockIdRegEx: 'null'
#    capitalize: false
#    minDistanceBetweenStopsToDisambiguateHeadsigns: 1000.0
#    outputPathsAndStopsForGraphingRouteIds: 'null'
#    routeIdFilterRegEx: 'null'
#    tripIdFilterRegEx: 'null'
#    tripShortNameRegEx: 'null'
  holding:
#    controlStops: 'null'
    maxPredictionsForHoldingTimeCalculation: 3
    plannedHeadwayMsec: 540000
    regenerateondeparture: false
    storeHoldingTimes: true
    usearrivalevents: true
    usearrivalpredictions: true
  monitoring:
    allowableNoAvlSecs: 300
    availableFreePhysicalMemoryThreshold: 10485760
    availableFreePhysicalMemoryThresholdGap: 157286400
    avlFeedEmailRecipients: monitoring@transitclock.org
    cpuThreshold: 0.99
    cpuThresholdGap: 0.1
#    emailRecipients: 'null'
    maxQueueFraction: 0.4
    maxQueueFractionGap: 0.1
    minPredictableBlocks: 0.5
    minPredictableBlocksGap: 0.25
    minimumPredictableVehicles: 3
    retryTimeoutSecs: 5
    secondsBetweenMonitorinPolling: 120
    usableDiskSpaceThreshold: 1073741824
    usableDiskSpaceThresholdGap: 104857600
#  predAccuracy:
#    gtfsTripUpdateUrl: http://127.0.0.1:8091/trip-updates
#    maxEarlynessComparedToPredictionMsec: 900000
#    maxLatenessComparedToPredictionMsec: 1500000
#    maxPredStalenessMinutes: 15
#    maxPredTimeMinutes: 15
#    maxRandomStopSelectionsPerTrip: 100
#    pollingRateMsec: 240000
#    stopsPerTrip: 5
  prediction:
    data:
      kalman:
        min-days: 3
        max-days: 5
        max-days-to-search: 21
        percentagePredictionMethodDifferencene: 50
        thresholdForDifferenceEventLog: 60000
    rls:
      lambda: 0.9
  service:
    minutesIntoMorningToIncludePreviousServiceIds: 240
  timeout:
    allowableNoAvlAfterSchedDepartSecs: 360
    allowableNoAvlSecs: 360
    pollingRateSecs: 60
    removeTimedOutVehiclesFromVehicleDataCache: false
  travelTimes:
    resetEarlyTerminalDepartures: true
    fractionLimitForStopTimes: 0.7
    fractionLimitForTravelTimes: 0.7
    maxSegmentSpeedMps: 27.0
    maxTravelTimeSegmentLength: 250.0
    minSegmentSpeedMps: 0.0
  tripdatacache:
    tripDataCacheMaxAgeSec: 1296000
  updates:
    pageDbReads: true
    pageSize: 50000
  web:
    mapTileCopyright: MapQuest
    mapTileUrl: http://otile4.mqcdn.com/tiles/1.0.0/osm/{z}/{x}/{y}.png
