services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: transitclock
      POSTGRES_DB: transitclock
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
  gtfsrt-validator:
    image: ghcr.io/mobilitydata/gtfs-realtime-validator:latest
    ports:
      - "9090:8080"
  transitclock:
    build:
      context: .
    image: transittrack-server:latest
    depends_on:
      - db
    environment:
      AGENCYID: "AGENCY_ID"
      AGENCYNAME: AGENCY
      TZ: "Europe/Warsaw"
      GTFS_URL: https://gtfs.pl/download/gtfs.zip
      GTFSRTVEHICLEPOSITIONS: https://host.pl/vehiclePositions.pb
      PGPASSWORD: transitclock
      POSTGRES_PORT_5432_TCP_ADDR: db
      POSTGRES_PORT_5432_TCP_PORT: 5432
    ports:
      - "8080:8080"
    command:
      - java
      - -jar
      - -Duser.timezone=Europe/Warsaw
      - app-3.0.0-SNAPSHOT.jar
      - --gtfs-url
      - https://gtfs.pl/download/gtfs.zip
