x-common-env: &common-env
  TZ: Europe/Warsaw
  POSTGRES_PASSWORD: transitclock

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      <<: *common-env
      POSTGRES_DB: AGENCY
    ports:
      - "9090:8080"
  transitclock:
    build:
      context: .
    image: transittrack-server:latest
    depends_on:
      - db
    environment:
      <<: *common-env
      AGENCYID: "AGENCY_ID"
      AGENCYNAME: AGENCY
      GTFS_URL: https://gtfs.pl/download/gtfs.zip
      GTFSRTVEHICLEPOSITIONS: https://host.pl/vehiclePositions.pb
      PGPASSWORD: transitclock
      POSTGRES_PORT_5432_TCP_ADDR: db
      POSTGRES_PORT_5432_TCP_PORT: 5432
    ports:
      - "8080:8080"
    command:
      - java
      - -jar
      - -Duser.timezone=Europe/Warsaw
      - app-3.0.0-SNAPSHOT.jar
      - --gtfs-url
      - https://gtfs.pl/download/gtfs.zip
