services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: transitclock
      POSTGRES_DB: NAME
    ports:
      - "5432:5432"
  gtfsrt-validator:
    image: ghcr.io/mobilitydata/gtfs-realtime-validator:latest
    ports:
      - "9090:8080"
  transitclock:
    image: wkulesza/transitclock-server:latest
    depends_on:
      - db
    environment:
      AGENCYID: 1
      AGENCYNAME: NAME
      TZ: "Europe/Warsaw"
      GTFSURL: https://example.com/gtfs.zip
      GTFSRTVEHICLEPOSITIONS: https://example.com/gtfs-rt.pb
      PGPASSWORD: transitclock
      POSTGRES_PORT_5432_TCP_ADDR: db
      POSTGRES_PORT_5432_TCP_PORT: 5432
      MINLONGITUDE: 10
      MAXLONGITUDE: 25
      MINLATITUDE: 50
      MAXLATITUDE: 55
      REFRESHINTERVAL: 15
    ports:
      - "8080:8080"
    command:
      - --gtfs-url
      - https://example.com/gtfs.zip
