/* (C)2023 */
package org.transitclock.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.csv.CsvMapper;
import com.fasterxml.jackson.dataformat.csv.CsvSchema;
import lombok.SneakyThrows;
import lombok.extern.slf4j.Slf4j;
import org.hibernate.Session;
import org.transitclock.core.AvlProcessor;
import org.transitclock.core.TemporalMatch;
import org.transitclock.core.VehicleState;
import org.transitclock.core.avl.AvlExecutor;
import org.transitclock.core.dataCache.PredictionDataCache;
import org.transitclock.core.dataCache.VehicleDataCache;
import org.transitclock.core.dataCache.VehicleStateManager;
import org.transitclock.core.reports.GenericJsonQuery;
import org.transitclock.domain.ApiKeyManager;
import org.transitclock.domain.hibernate.HibernateUtils;
import org.transitclock.domain.structs.AvlReport;
import org.transitclock.domain.structs.ExportTable;
import org.transitclock.domain.structs.VehicleEvent;
import org.transitclock.domain.structs.VehicleToBlockConfig;
import org.transitclock.domain.webstructs.ApiKey;
import org.transitclock.service.contract.CommandsInterface;
import org.transitclock.service.dto.IpcAvl;
import org.transitclock.service.dto.IpcVehicleComplete;

import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Collection;
import java.util.Date;

import static org.transitclock.domain.structs.ExportTable.deleteExportTableRecord;

@Slf4j
public class CommandsServiceImpl implements CommandsInterface {

    // Should only be accessed as singleton class
    private static CommandsServiceImpl singleton;

    public CommandsServiceImpl() {
    }

    public static CommandsInterface instance() {
        return singleton;
    }

    /**
     * Starts up the CommandsServer so that RMI calls can be used to control the server. This will
     * automatically cause the object to continue to run and serve requests.
     *
     * @return the singleton CommandsServer object. Usually does not need to used since the server
     * will be fully running.
     */
    public static CommandsServiceImpl start() {
        if (singleton == null) {
            singleton = new CommandsServiceImpl();
        }

        return singleton;
    }

    /**
     * Called on server side via RMI when AVL data is to be processed
     *
     * @param avlData AVL data sent to server
     * @return Null if OK, otherwise an error message
     */
    @Override
    public String pushAvl(IpcAvl avlData) {
        // Use AvlExecutor to actually process the data using a thread executor
        AvlReport avlReport = new AvlReport(avlData);
        logger.debug("Processing AVL report {}", avlReport);
        AvlExecutor.getInstance().processAvlReport(avlReport);

        // Return that was successful
        return null;
    }

    /**
     * Called on server side via RMI when AVL data is to be processed
     *
     * @param avlDataCollection AVL data sent to server
     * @return Null if OK, otherwise an error message
     */
    @Override
    public String pushAvl(Collection<IpcAvl> avlDataCollection) {
        for (IpcAvl avlData : avlDataCollection) {
            // Use AvlExecutor to actually process the data using a thread executor
            AvlReport avlReport = new AvlReport(avlData);
            logger.debug("Processing AVL report {}", avlReport);
            AvlExecutor.getInstance().processAvlReport(avlReport);
        }

        // Return that was successful
        return null;
    }

    @Override
    public void setVehicleUnpredictable(String vehicleId) {

        VehicleState vehicleState = VehicleStateManager.getInstance().getVehicleState(vehicleId);

        // Create a VehicleEvent to record what happened
        AvlReport avlReport = vehicleState.getAvlReport();
        TemporalMatch lastMatch = vehicleState.getMatch();
        boolean wasPredictable = vehicleState.isPredictable();

        String vehicleEvent = "Command called to make vehicleId unpredicable. ";
        String eventDescription = "Command called to make vehicleId unpredicable. ";
        VehicleEvent.create(
                avlReport,
                lastMatch,
                vehicleEvent,
                eventDescription,
                false, // predictable
                wasPredictable, // becameUnpredictable
                null); // supervisor

        // Update the state of the vehicle
        vehicleState.setMatch(null);

        // Remove the predictions that were generated by the vehicle
        PredictionDataCache.getInstance().removePredictions(vehicleState);

        // Update VehicleDataCache with the new state for the vehicle
        VehicleDataCache.getInstance().updateVehicle(vehicleState);
    }

    private VehicleState getVehicleStateForTrip(String tripId, LocalDateTime _startTripTime) {
        /* The startTripTime parameter should not be null if noSchedule */
        long startTripTime = 0;
        if (_startTripTime != null)
            startTripTime = _startTripTime.atZone(ZoneId.systemDefault()).toEpochSecond() * 1000L;
        /*
         * Get the vehicle associated to the tripId. Is it possible to have more than 1 bus with the
         * same tripId??
         */
        Collection<IpcVehicleComplete> ipcVehicleCompletList =
                VehicleDataCache.getInstance().getVehiclesIncludingSchedBasedOnes();
        VehicleState vehicleState = null;
        for (IpcVehicleComplete _ipcVehicle : ipcVehicleCompletList) {

            if (_ipcVehicle.getTripId() != null && _ipcVehicle.getTripId().compareTo(tripId) == 0) {
                VehicleState _vehicleState = VehicleStateManager.getInstance().getVehicleState(_ipcVehicle.getId());
                boolean noSchedule = _vehicleState.getTrip().isNoSchedule();
                if (!noSchedule) {
                    vehicleState = _vehicleState;
                    break;
                } else if (noSchedule && _ipcVehicle.getTripStartEpochTime() == startTripTime) {
                    vehicleState = _vehicleState;
                    break;
                }
            }
        }
        return vehicleState;
    }

    @Override
    public String cancelTrip(String tripId, LocalDateTime startTripTime) {

        // String vehicleId=	"block_" + blockId + "_schedBasedVehicle";
        VehicleState vehicleState = this.getVehicleStateForTrip(tripId, startTripTime);
        if (vehicleState == null) return "TripId id is not currently available";

        AvlReport avlReport = vehicleState.getAvlReport();
        if (avlReport != null) {
            vehicleState.setCanceled(true);
            VehicleDataCache.getInstance().updateVehicle(vehicleState);
            AvlProcessor.getInstance().processAvlReport(avlReport);
            return null;
        } else return "vehicle with this trip id does not have avl report";
    }

    @Override
    public String reenableTrip(String tripId, LocalDateTime startTripTime) {

        // String vehicleId=	"block_" + blockId + "_schedBasedVehicle";
        VehicleState vehicleState = this.getVehicleStateForTrip(tripId, startTripTime);
        if (vehicleState == null) return "TripId id is not currently available";
        AvlReport avlReport = vehicleState.getAvlReport();
        if (avlReport != null) {
            vehicleState.setCanceled(false);
            VehicleDataCache.getInstance().updateVehicle(vehicleState);
            AvlProcessor.getInstance().processAvlReport(avlReport);
            return null;
        } else return "vehicle with this trip id does not have avl report";
    }

    @Override
    public String addVehicleToBlock(
            String vehicleId, String blockId, String tripId, Date assignmentDate, Date validFrom, Date validTo) {
        VehicleToBlockConfig.create(vehicleId, blockId, tripId, assignmentDate, validFrom, validTo);
        return null;
    }

    @Override
    public void removeVehicleToBlock(long id) {
        Session session = HibernateUtils.getSession();
        try {
            VehicleToBlockConfig.deleteVehicleToBlockConfig(id, session);
            session.close();
        } catch (Exception ex) {
            session.close();
        }
    }

    @SneakyThrows
    @Override
    public void addJsonAsCSVExport(String data, final String fileName) {
        String preparedData = "";
        if(data.contains("{\"data\": "))
            preparedData= data.replaceFirst("^\\{\"data\":\\s*", "").replaceFirst("}$", "");

        try {
            JsonNode jsonTree = new ObjectMapper().readTree(preparedData);
            JsonNode firstObject = jsonTree.elements().next();


            CsvSchema.Builder csvSchemaBuilder = CsvSchema.builder();
            firstObject.fieldNames().forEachRemaining(fieldName -> {
                csvSchemaBuilder.addColumn(fieldName);
            });

            CsvSchema csvSchema = csvSchemaBuilder.build().withHeader();
            CsvMapper csvMapper = new CsvMapper();
            byte[] file = csvMapper.writerFor(JsonNode.class)
                    .with(csvSchema).writeValueAsBytes(jsonTree);

            ExportTable.create(new ExportTable(new Date(), 4, 3, fileName, file));
        }  catch (Exception ex) {
            Session session = HibernateUtils.getSession();
            deleteExportTableRecord(fileName, session);
            session.close();
            logger.warn("Something went wrong wile adding export file to DB: {}", ex.getMessage());
            throw new RuntimeException(ex);
        }
    }

    @Override
    public ExportTable removeExportById(int id) {
        try (var session = HibernateUtils.getSession()) {
            var exportsToDelete = ExportTable.getExport(session, id);
            if (!exportsToDelete.isEmpty() && exportsToDelete.get(0).getId() == id) {
                ExportTable.deleteExportTableRecord(id, session);
                boolean isDeleted = ExportTable.getExport(session, id).isEmpty();
                if (isDeleted) return exportsToDelete.get(0);
            }
        }
        throw new IllegalArgumentException("Export with id: '" + id + "' - is not found!");
    }

    @Override
    public String addApiKey(String applicationName, String applicationUrl,
                            String email, String phone, String description, boolean secret) throws RuntimeException {
        try {
            ApiKey key = ApiKeyManager.getInstance()
                    .generateApiKey(applicationName, applicationUrl, email, phone, description, secret);
            logger.info("Successfully created and added application key for {} to database. ", key.getApplicationName());
            return key.getApplicationKey();
        } catch (Exception exception) {
            logger.error(exception.getMessage());
            throw exception;
        }
    }

    @Override
    public String removeApiKey(String apiKey) throws RuntimeException {

        try {
            String result = ApiKeyManager.getInstance().deleteKey(apiKey);
            logger.info("Successfully deleted key for {} from database. ", apiKey);
            return result;

        } catch (Exception exception) {
            logger.error(exception.getMessage());
            throw exception;
        }
    }
}
